
name: Trigger Backend Build

on:
  push:
    branches: [ main ]

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger backend workflow
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO2_TOKEN }}
          repository: your-username/backend
          event-type: start-build
